/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedAccountingRouteImport } from './routes/_authenticated/accounting'
import { Route as AuthenticatedAiAssistantRouteImport } from './routes/_authenticated/ai-assistant'
import { Route as AuthenticatedBankingRouteImport } from './routes/_authenticated/banking'
import { Route as AuthenticatedContactsRouteImport } from './routes/_authenticated/contacts'
import { Route as AuthenticatedHelpRouteImport } from './routes/_authenticated/help'
import { Route as AuthenticatedProductsServicesRouteImport } from './routes/_authenticated/products-services'
import { Route as AuthenticatedPurchasesRouteImport } from './routes/_authenticated/purchases'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedSalesRouteImport } from './routes/_authenticated/sales'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'

const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/_authenticated/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountingRoute = AuthenticatedAccountingRouteImport.update({
  id: '/_authenticated/accounting',
  path: '/accounting',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAiAssistantRoute =
  AuthenticatedAiAssistantRouteImport.update({
    id: '/_authenticated/ai-assistant',
    path: '/ai-assistant',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedBankingRoute = AuthenticatedBankingRouteImport.update({
  id: '/_authenticated/banking',
  path: '/banking',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedContactsRoute = AuthenticatedContactsRouteImport.update({
  id: '/_authenticated/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedHelpRoute = AuthenticatedHelpRouteImport.update({
  id: '/_authenticated/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProductsServicesRoute =
  AuthenticatedProductsServicesRouteImport.update({
    id: '/_authenticated/products-services',
    path: '/products-services',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedPurchasesRoute = AuthenticatedPurchasesRouteImport.update({
  id: '/_authenticated/purchases',
  path: '/purchases',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/_authenticated/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSalesRoute = AuthenticatedSalesRouteImport.update({
  id: '/_authenticated/sales',
  path: '/sales',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/_authenticated/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/accounting': typeof AuthenticatedAccountingRoute
  '/ai-assistant': typeof AuthenticatedAiAssistantRoute
  '/banking': typeof AuthenticatedBankingRoute
  '/contacts': typeof AuthenticatedContactsRoute
  '/help': typeof AuthenticatedHelpRoute
  '/products-services': typeof AuthenticatedProductsServicesRoute
  '/purchases': typeof AuthenticatedPurchasesRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/sales': typeof AuthenticatedSalesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesByTo {
  '/accounting': typeof AuthenticatedAccountingRoute
  '/ai-assistant': typeof AuthenticatedAiAssistantRoute
  '/banking': typeof AuthenticatedBankingRoute
  '/contacts': typeof AuthenticatedContactsRoute
  '/help': typeof AuthenticatedHelpRoute
  '/products-services': typeof AuthenticatedProductsServicesRoute
  '/purchases': typeof AuthenticatedPurchasesRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/sales': typeof AuthenticatedSalesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated/accounting': typeof AuthenticatedAccountingRoute
  '/_authenticated/ai-assistant': typeof AuthenticatedAiAssistantRoute
  '/_authenticated/banking': typeof AuthenticatedBankingRoute
  '/_authenticated/contacts': typeof AuthenticatedContactsRoute
  '/_authenticated/help': typeof AuthenticatedHelpRoute
  '/_authenticated/products-services': typeof AuthenticatedProductsServicesRoute
  '/_authenticated/purchases': typeof AuthenticatedPurchasesRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/sales': typeof AuthenticatedSalesRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/accounting'
    | '/ai-assistant'
    | '/banking'
    | '/contacts'
    | '/help'
    | '/products-services'
    | '/purchases'
    | '/reports'
    | '/sales'
    | '/settings'
    | '/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/accounting'
    | '/ai-assistant'
    | '/banking'
    | '/contacts'
    | '/help'
    | '/products-services'
    | '/purchases'
    | '/reports'
    | '/sales'
    | '/settings'
    | '/'
  id:
    | '__root__'
    | '/_authenticated/accounting'
    | '/_authenticated/ai-assistant'
    | '/_authenticated/banking'
    | '/_authenticated/contacts'
    | '/_authenticated/help'
    | '/_authenticated/products-services'
    | '/_authenticated/purchases'
    | '/_authenticated/reports'
    | '/_authenticated/sales'
    | '/_authenticated/settings'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedAccountingRoute: typeof AuthenticatedAccountingRoute
  AuthenticatedAiAssistantRoute: typeof AuthenticatedAiAssistantRoute
  AuthenticatedBankingRoute: typeof AuthenticatedBankingRoute
  AuthenticatedContactsRoute: typeof AuthenticatedContactsRoute
  AuthenticatedHelpRoute: typeof AuthenticatedHelpRoute
  AuthenticatedProductsServicesRoute: typeof AuthenticatedProductsServicesRoute
  AuthenticatedPurchasesRoute: typeof AuthenticatedPurchasesRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSalesRoute: typeof AuthenticatedSalesRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/accounting': {
      id: '/_authenticated/accounting'
      path: '/accounting'
      fullPath: '/accounting'
      preLoaderRoute: typeof AuthenticatedAccountingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/ai-assistant': {
      id: '/_authenticated/ai-assistant'
      path: '/ai-assistant'
      fullPath: '/ai-assistant'
      preLoaderRoute: typeof AuthenticatedAiAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/banking': {
      id: '/_authenticated/banking'
      path: '/banking'
      fullPath: '/banking'
      preLoaderRoute: typeof AuthenticatedBankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/contacts': {
      id: '/_authenticated/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof AuthenticatedContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/help': {
      id: '/_authenticated/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof AuthenticatedHelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/products-services': {
      id: '/_authenticated/products-services'
      path: '/products-services'
      fullPath: '/products-services'
      preLoaderRoute: typeof AuthenticatedProductsServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/purchases': {
      id: '/_authenticated/purchases'
      path: '/purchases'
      fullPath: '/purchases'
      preLoaderRoute: typeof AuthenticatedPurchasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/sales': {
      id: '/_authenticated/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof AuthenticatedSalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedAccountingRoute: AuthenticatedAccountingRoute,
  AuthenticatedAiAssistantRoute: AuthenticatedAiAssistantRoute,
  AuthenticatedBankingRoute: AuthenticatedBankingRoute,
  AuthenticatedContactsRoute: AuthenticatedContactsRoute,
  AuthenticatedHelpRoute: AuthenticatedHelpRoute,
  AuthenticatedProductsServicesRoute: AuthenticatedProductsServicesRoute,
  AuthenticatedPurchasesRoute: AuthenticatedPurchasesRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSalesRoute: AuthenticatedSalesRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
